# Generated by Django 5.1.3 on 2024-12-07 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_alter_car_image_url'),
        ('posts', '0002_carpost_author_alter_carpost_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='carpost',
            name='related_cars',
            field=models.ManyToManyField(blank=True, to='cars.car'),
        ),
    ]
